// Q1. Given an array of integers, return indices of two numbers such that they add up to a target. (MUST)
// Q2. Given an array of stock prices, find the maximum profit from one buy and one sell. (MUST)
// Q3. Given an integer array, determine if any value appears more than once. (MUST)
// Q4. Given an integer array, return an array where each element is the product of all elements except itself. (MUST)
// Q5. Given an integer array, find the contiguous subarray with the largest sum. (MUST)
// Q6. Given an integer array, find the contiguous subarray with the largest product. (OPTIONAL)
// Q7. Given a rotated sorted array, find the minimum element. (MUST)
// Q8. Given a rotated sorted array and a target value, return its index or −1. (MUST)
// Q9. Given an integer array, find all unique triplets that sum to zero. (MUST)
// Q10. Given an array of heights, find the maximum area of water a container can store. (OPTIONAL)

// Q11. Given two integers, calculate their sum without using + or −. (OPTIONAL)
// Q12. Given an integer, return the number of 1 bits in its binary representation. (MUST)
// Q13. Given an integer n, return an array where each index contains the count of 1 bits. (OPTIONAL)
// Q14. Given an array containing numbers from 0 to n, find the missing number. (MUST)
// Q15. Given a 32-bit unsigned integer, reverse its bits. (OPTIONAL)

// Q16. Given n steps, determine the number of distinct ways to reach the top. (MUST)
// Q17. Given coin denominations and a total amount, find the minimum number of coins required. (MUST)
// Q18. Given an integer array, find the length of the longest increasing subsequence. (MUST)
// Q19. Given two strings, find the length of their longest common subsequence. (OPTIONAL)
// Q20. Given a string and a dictionary, determine if the string can be segmented into dictionary words. (MUST)
// Q21. Given candidate numbers and a target, return all unique combinations that sum to the target. (MUST)
// Q22. Given a list of houses, find the maximum amount you can rob without robbing adjacent houses. (MUST)
// Q23. Given houses arranged in a circle, find the maximum amount you can rob. (OPTIONAL)
// Q24. Given a string of digits, return the total number of ways to decode it. (OPTIONAL)
// Q25. Given an m×n grid, find the number of unique paths from top-left to bottom-right. (MUST)

// Q26. Given a reference to a graph node, create a deep copy of the entire graph. (OPTIONAL)
// Q27. Given courses and prerequisites, determine if all courses can be completed. (MUST)
// Q28. Given a matrix of heights, find all cells where water can flow to both oceans. (OPTIONAL)
// Q29. Given a grid of 1s and 0s, count the number of islands. (MUST)
// Q30. Given an unsorted array, find the length of the longest consecutive sequence. (MUST)
